version: "3.3"
services: 
    meguapark:
        container_name: meguapark_api
        build: .
        ports: 
            - "3000:3000"
        env_file: 
            - ".env"
        image: everacosta/meguapark_api:0.3